name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action
        with:
          who-to-greet: Roger
      - name: Log greeting time
        run: "${{ steps.greet.outputs.time}}"
        